import { useState } from 'react'
import Tabla from '../components/Tabla'
import EtiquetaEstado from '../components/EtiquetaEstado'
export default function Prestamos({ prestamos,personas,items,registrar }) {
 const [mostrar,setMostrar]=useState(false); const [mensaje,setMensaje]=useState(''); const [formulario,setFormulario]=useState({personaId:'',itemId:'',lugarUso:'DOMICILIO'})
 function enviar(e){e.preventDefault();registrar(formulario);setMensaje('Solicitud enviada. El servidor validará las reglas del préstamo.');setMostrar(false)}
 const columnas=[{clave:'id',titulo:'N.º'},{clave:'persona',titulo:'PERSONA'},{clave:'item',titulo:'BIEN'},{clave:'entrega',titulo:'ENTREGA'},{clave:'devolucion',titulo:'DEVOLUCIÓN'},{clave:'estado',titulo:'ESTADO',render:f=><EtiquetaEstado estado={f.estado}/>},{clave:'accion',titulo:'ACCIÓN',render:()=> <button className="enlace">Registrar devolución</button>}]
 return <><div className="acciones"><button className="boton primario" onClick={()=>setMostrar(!mostrar)}>+ Registrar préstamo</button></div>{mensaje&&<div className="aviso correcto-aviso">✓ {mensaje}</div>}{mostrar&&<form className="formulario panel" onSubmit={enviar}><h2>Nuevo préstamo</h2><p>Selecciona los datos. Las restricciones serán evaluadas por el backend.</p><div className="campos"><label>Persona<select required value={formulario.personaId} onChange={e=>setFormulario({...formulario,personaId:e.target.value})}><option value="">Seleccionar…</option>{personas.map(p=><option value={p.id} key={p.id}>{p.nombre} — {p.tipo}</option>)}</select></label><label>Bien<select required value={formulario.itemId} onChange={e=>setFormulario({...formulario,itemId:e.target.value})}><option value="">Seleccionar…</option>{items.map(i=><option value={i.id} key={i.id}>{i.nombre}</option>)}</select></label><label>Lugar de uso<select value={formulario.lugarUso} onChange={e=>setFormulario({...formulario,lugarUso:e.target.value})}><option value="DOMICILIO">Domicilio</option><option value="SALA">Sala institucional</option></select></label></div><button className="boton primario">Enviar solicitud</button></form>}<section className="panel"><Tabla filas={prestamos} columnas={columnas}/></section></>
}
